name = "hotdog-counter"
main = "src/worker.js"
compatibility_date = "2024-11-11"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "hotdog-db"
database_id = "73a79a20-ae52-4968-a3a6-bb8a3487cce2"
