name = "hotdog-counter"
main = "src/worker.js"
compatibility_date = "2024-11-11"

# account_id gets appended by the workflow step, or set it here if you prefer:
# account_id = "YOUR_ACCOUNT_ID"

[[d1_databases]]
binding = "DB"
database_name = "hotdog-db"
database_id = "YOUR-D1-ID"

[env.staging]
# Example: use a different DB for staging
# [[env.staging.d1_databases]]
# binding = "DB"
# database_name = "hotdog-db-staging"
# database_id = "STAGING-D1-ID"
